name: Books Service CI/CD

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: rbutechnologies
  IMAGE_NAME: books-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Maven Build
        run: |
          mvn clean package -DskipTests
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
          docker push $DOCKER_USERNAME/$IMAGE_NAME:latest